spring:
  datasource:
        url: jdbc:oracle:thin:@localhost:1521:root
        username: root
        password: 1234
        driver-class-name: oracle.jdbc.driver.OracleDriver
        

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml  configuration:
    map-underscore-to-camel-case: true       