spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:root
    driver-class-name: oracle.jdbc.OracleDriver
    username: root
    password: 1234

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: mapper/**/*Mapper.xml
  type-aliases-package: com.project.bit.foo.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: logback-spring.xml

server:
  port: 8080