spring:
  datasource:
        url: jdbc:oracle:thin:@localhost:1521:root
        driver-class-name: oracle.jdbc.OracleDriver
        username: root
        password: 1234
---     
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.project.bit.foo.domain
  configuration:
    mapUnderscoreToCamelCase: true
